edit2

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,8 +11,13 @@ before_install:
 #   - gem install logger
   # - gem install faraday-net_http -v '3.3s.0'
 before_deploy:
-  - if [ -z "$GITHUB_TOKEN" ]; then echo "GITHUB_TOKEN is missing"; exit 1; else echo "GITHUB_TOKEN found"; fi
-
+  - |
+    if [[ -z "$GITHUB_TOKEN" ]]; then 
+      echo "ERROR: GITHUB_TOKEN is missing. Please set it in Travis CI settings.";
+      exit 1;
+    else 
+      echo "GITHUB_TOKEN is present.";
+    fi
 deploy:
   provider: pages
   skip_cleanup: true
