back to basic conf

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,22 +2,22 @@ language: node_js
 node_js:
   - "stable"
 dist: focal
-before_install:
-  - gem install bundler
+# before_install:
+#   - gem install bundler
 
 # before_deploy:
 #   - yes | gem update --system --force
 #   - gem install uri
 #   - gem install logger
   # - gem install faraday-net_http -v '3.3s.0'
-before_deploy:
-  - |
-    if [[ -z "$GITHUB_TOKEN" ]]; then 
-      echo "ERROR: GITHUB_TOKEN is missing. Please set it in Travis CI settings.";
-      exit 1;
-    else 
-      echo "GITHUB_TOKEN is present.";
-    fi
+# before_deploy:
+#   - |
+#     if [[ -z "$GITHUB_TOKEN" ]]; then 
+#       echo "ERROR: GITHUB_TOKEN is missing. Please set it in Travis CI settings.";
+#       exit 1;
+#     else 
+#       echo "GITHUB_TOKEN is present.";
+#     fi
 deploy:
   provider: pages
   skip_cleanup: true
